from navigation.horwbotstatemachine import HorwbotStateMachine

m = HorwbotStateMachine()
print(m.state)
m.initializing()
print(m.state)
m.startSearching()
print(m.state)
m.moveForward()
print(m.state)
m.backToSearch()
print(m.state)
m.moveBackward()
print(m.state)
m.backToSearch()
print(m.state)
m.crossing()
print(m.state)
m.backToSearch()
print(m.state)
m.stopping()
print(m.state)
m.backToSearch()
print(m.state)
m.goToEmergency()
print(m.state)
m.backToSearch()
print(m.state)
m.goToError()
print(m.state)
m.errorHandling()
print(m.state)
m.startSearching()
print(m.state)
m.endParcour()
print(m.state)
